# Normal Information 
CC=gcc
FILE_EXT=c

FLAGS_DEBUG= -g -Wall 
FLAGS_RELEASE= -O3


#Project info
PROJECT_PATH= ../../../library/linux/3rdparty/
PROJECT=zlib

SRC_DIR=../src
INCLUDE_DIR= -I../include

#Source File 
SRC=  adler32.c \
	  compress.c \
	  crc32.c \
	  deflate.c \
	  gzclose.c \
	  gzlib.c \
	  gzread.c \
	  gzwrite.c \
	  infback.c \
	  inffast.c \
	  inflate.c \
	  inftrees.c \
	  trees.c \
	  uncompr.c \
	  zutil.c  \


include ../../../MK_BUILD_STATIC_LIB

