main:
	../../tool/$(TOLUA) -L "../basic.lua" -o ../../src/luaexport/FsLibAudioExport.cc FsLibAudio.pkg
	../../tool/$(TOLUA) -L "../basic.lua" -o ../../src/luaexport/FsLibNetworkExport.cc FsLibNetwork.pkg



