/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_faeris_lib_FsAndroidInfo */

#ifndef _Included_org_faeris_lib_FsAndroidInfo
#define _Included_org_faeris_lib_FsAndroidInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_faeris_lib_FsAndroidInfo
 * Method:    setApkPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_faeris_lib_FsAndroidInfo_setApkName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_faeris_lib_FsAndroidInfo
 * Method:    setSourceDir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_faeris_lib_FsAndroidInfo_setApkPath
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
