/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_faeris_lib_FsEngine */

#ifndef _Included_org_faeris_lib_FsEngine
#define _Included_org_faeris_lib_FsEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_faeris_lib_FsEngine
 * Method:    moduleInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_faeris_lib_FsEngine_moduleInit
  (JNIEnv *, jclass);

/*
 * Class:     org_faeris_lib_FsEngine
 * Method:    moduleExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_faeris_lib_FsEngine_moduleExit
  (JNIEnv *, jclass);

/*
 * Class:     org_faeris_lib_FsEngine
 * Method:    onForeground
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_faeris_lib_FsEngine_onForeground
  (JNIEnv *, jclass);

/*
 * Class:     org_faeris_lib_FsEngine
 * Method:    onBackground
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_faeris_lib_FsEngine_onBackground
  (JNIEnv *, jclass);

/*
 * Class:     org_faeris_lib_FsEngine
 * Method:    onTouchBegin
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_faeris_lib_FsEngine_onTouchBegin
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_faeris_lib_FsEngine
 * Method:    onTouchMove
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_faeris_lib_FsEngine_onTouchMove
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_faeris_lib_FsEngine
 * Method:    onTouchEnd
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_faeris_lib_FsEngine_onTouchEnd
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_faeris_lib_FsEngine
 * Method:    onTouchCancel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_faeris_lib_FsEngine_onTouchCancel
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_faeris_lib_FsEngine
 * Method:    onResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_faeris_lib_FsEngine_onResize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_faeris_lib_FsEngine
 * Method:    onViewCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_faeris_lib_FsEngine_onViewCreated
  (JNIEnv *, jclass);

/*
 * Class:     org_faeris_lib_FsEngine
 * Method:    onUpdate
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_faeris_lib_FsEngine_onUpdate
  (JNIEnv *, jclass, jfloat);

#ifdef __cplusplus
}
#endif
#endif
