# Normal Information 
CC=gcc
FILE_EXT=c

FLAGS_DEBUG= -g -Wall -Werror 
FLAGS_RELEASE= -O3 


#Project infor 
PROJECT_PATH= ../../../library/linux/
PROJECT=libpng
SRC_DIR=../src
INCLUDE_DIR= -I./include -I../../zlib/include

#Source File 
SRC=  png.c \
	  pngerror.c \
	  pngget.c \
	  pngset.c \
	  pngmem.c \
	  pngtrans.c \
	  pngpread.c \
	  pngread.c \
	  pngrio.c \
	  pngrtran.c \
	  pngrutil.c \
	  pngwio.c \
	  pngwrite.c \
	  pngwtran.c \
	  pngwutil.c \


include  ../../../MK_BUILD_STATIC_LIB



