/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rwhz_minder_Fs_r3rdPartyJni */

#ifndef _Included_com_ihuizhi_minder_Fs_r3rdPartyJni
#define _Included_com_ihuizhi_minder_Fs_r3rdPartyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rwhz_minder_Fs_r3rdPartyJni
 * Method:    onForeground
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ihuizhi_minder_Fs_1r3rdPartyJni_onForeground
  (JNIEnv *, jclass);

/*
 * Class:     com_rwhz_minder_Fs_r3rdPartyJni
 * Method:    NativeBillingPointCB
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_ihuizhi_minder_Fs_1r3rdPartyJni_NativeBillingPointCB
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_rwhz_minder_Fs_r3rdPartyJni
 * Method:    NativeCheckUpdateCB
 * Signature: (Ljava/lang/Long;I)V
 */
JNIEXPORT void JNICALL Java_com_ihuizhi_minder_Fs_1r3rdPartyJni_NativeCheckUpdateCB
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
