# Normal Information 
CC=gcc
FILE_EXT=c

FLAGS_DEBUG= -g -Wall 
FLAGS_RELEASE= -O3 

#Project infor 
PROJECT_PATH= ../../../library/linux/
PROJECT=tolua++

SRC_DIR=../src
INCLUDE_DIR= -I../include  -I../../lua/include

#Source File 
SRC=  tolua_event.c \
	  tolua_is.c \
	  tolua_map.c \
	  tolua_push.c \
	  tolua_to.c \

include ../../../MK_BUILD_STATIC_LIB 

