# Normal Information 
CC=gcc
FILE_EXT=c

FLAGS_DEBUG= -g -Wall 
FLAGS_RELEASE= -O3

#Project infor 
PROJECT_PATH= ../../../library/linux/
PROJECT=minizip

SRC_DIR=../src
INCLUDE_DIR= -I../include  

#Source File 
SRC=  ioapi.c \
	  unzip.c \


include ../../../MK_BUILD_STATIC_LIB 

