/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_faeris_lib_Fs_Jni */

#ifndef _Included_com_faeris_lib_Fs_Jni
#define _Included_com_faeris_lib_Fs_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_faeris_lib_Fs_Jni
 * Method:    moduleInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_faeris_lib_Fs_1Jni_moduleInit
  (JNIEnv *, jclass);

/*
 * Class:     com_faeris_lib_Fs_Jni
 * Method:    moduleExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_faeris_lib_Fs_1Jni_moduleExit
  (JNIEnv *, jclass);

/*
 * Class:     com_faeris_lib_Fs_Jni
 * Method:    onForeground
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_faeris_lib_Fs_1Jni_onForeground
  (JNIEnv *, jclass);

/*
 * Class:     com_faeris_lib_Fs_Jni
 * Method:    onBackground
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_faeris_lib_Fs_1Jni_onBackground
  (JNIEnv *, jclass);

/*
 * Class:     com_faeris_lib_Fs_Jni
 * Method:    onTouchesBegin
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_faeris_lib_Fs_1Jni_onTouchesBegin
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_faeris_lib_Fs_Jni
 * Method:    onTouchesPointerDown
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_faeris_lib_Fs_1Jni_onTouchesPointerDown
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_faeris_lib_Fs_Jni
 * Method:    onTouchesMove
 * Signature: (I[I[F[F)V
 */
JNIEXPORT void JNICALL Java_com_faeris_lib_Fs_1Jni_onTouchesMove
  (JNIEnv *, jclass, jint, jintArray, jfloatArray, jfloatArray);

/*
 * Class:     com_faeris_lib_Fs_Jni
 * Method:    onTouchesPointerUp
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_faeris_lib_Fs_1Jni_onTouchesPointerUp
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_faeris_lib_Fs_Jni
 * Method:    onTouchesEnd
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_faeris_lib_Fs_1Jni_onTouchesEnd
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_faeris_lib_Fs_Jni
 * Method:    onKeyEventBack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_faeris_lib_Fs_1Jni_onKeyEventBack
  (JNIEnv *, jclass);

/*
 * Class:     com_faeris_lib_Fs_Jni
 * Method:    onKeyEventMenu
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_faeris_lib_Fs_1Jni_onKeyEventMenu
  (JNIEnv *, jclass);

/*
 * Class:     com_faeris_lib_Fs_Jni
 * Method:    onInputText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_faeris_lib_Fs_1Jni_onInputText(JNIEnv*,jclass,jstring);


/*
 * Class:     com_faeris_lib_Fs_Jni
 * Method:    onResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_faeris_lib_Fs_1Jni_onResize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_faeris_lib_Fs_Jni
 * Method:    onUpdate
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_com_faeris_lib_Fs_1Jni_onUpdate
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_faeris_lib_Fs_Jni
 * Method:    onDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_faeris_lib_Fs_1Jni_onDestroy
  (JNIEnv *, jclass);

/*
 * Class:     com_faeris_lib_Fs_Jni
 * Method:    setEnv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_faeris_lib_Fs_1Jni_setEnv
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_faeris_lib_Fs_Jni
 * Method:    schedulerStop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_faeris_lib_Fs_1Jni_schedulerStop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
